# src/main.py

def main():
    print("Hello, Jenkins!")
    
    # Optionally create an output file
    with open('output.txt', 'w') as f:
        f.write("This is an output file generated by Jenkins.")

if __name__ == "__main__":
    main()

